version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - '42124:42124'
      - '24678:24678'
  postgres:
    image: postgres:17.3
    restart: unless-stopped
    volumes:
      - neptun_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  redis:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    restart: unless-stopped
    volumes:
      - ./database/redis.conf:/etc/keydb/redis.conf
      - neptun_redis_data:/data
    ports:
      - 6379:6379

volumes:
  neptun_postgres_data:
    driver: local
  neptun_redis_data:
    driver: local
